### ISSUE TITLE
updating the xml files for latest addition in ICD10 

### ISSUE THREAD

**Issue by Karim-Baig** [StefanoTrv/simple_icd_10#2]
Please guide me in preparing and updating the xml file to include the latest additions in ICD 10 convention?

**Comment by StefanoTrv** [comment]
Hi, I'll be glad to help you. However this isn't the correct place to discuss about this, since this isn't exactly an "issue". I will close this issue, could you please open a new discussion in the [discussion section](https://github.com/StefanoTrv/simple_icd_10/discussions), where we can talk more freely about this matter?
Also, as far as I know, the version of ICD10 I use in this library is the most recent one. Maybe you are interested in ICD10CM? If so, I have created another library, really similar to this, that deals with ICD10CM codes: [simple_icd_10_cm](https://github.com/StefanoTrv/simple_icd_10_CM). I'll wait for more details in the discussion section ([here](https://github.com/StefanoTrv/simple_icd_10_CM/discussions) is the discussion section of simple_icd_10_cm, just in case). Have a nice day!

**Comment by Karim-Baig** [comment]
Hi Stefano, this actually helps a lot. Have you thought about creating a data structure (along similar lines) for HCPCS/CPT Codes. ?
